// <auto-generated />
namespace OptionWebsite.Migration.Records
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class seed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(seed));
        
        string IMigrationMetadata.Id
        {
            get { return "201510162336315_seed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
